
### OpenWeather Status 

GET http://api.openweathermap.org/data/2.5/forecast?q=osasco&units=metric&appid=968f89edcb450a633b853a5dda6760b2






### Create a new user

POST http://localhost:3000/api/users/user HTTP/1.1
content-type: application/json

{
    "email": "teste@admin.com.br",
    "password": "123456"
}

### Find one user (not used)

GET http://localhost:3000/api/users/nyudji@admin.com.br



### Find one user (extract token data)

GET http://localhost:3000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NjYzMjg1ODEsImV4cCI6MTc2NjMzMjE4MX0.GCj2_8Oj650yzXsZYwRxibvFpo88Ml7o5VrB0maAGUI



### Find all users

GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NjYzMjg1ODEsImV4cCI6MTc2NjMzMjE4MX0.GCj2_8Oj650yzXsZYwRxibvFpo88Ml7o5VrB0maAGUI


### Update one user

PATCH http://localhost:3000/api/users/69447d994b6cc5f61b84f4d9 HTTP/1.1
content-type: application/json

{
    "email": "salve@admin.com.br",
    "password": "123456789"
}


### Delete one user

DELETE http://localhost:3000/api/users/69447d994b6cc5f61b84f4d9 HTTP/1.1





### Generate access and refresh token

POST http://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
    "email": "teste@admin.com.br",
    "password": "123456"
}




### Request IA insights for weather logs

GET http://localhost:3000/api/insights/deepseek



### Export weather logs for csv

GET http://localhost:3000/api/weather/csv


### Export weather logs for xlsx

GET http://localhost:3000/api/weather/csv


###

GET http://localhost:3000/api/weather/logs



